// Package theme defines the visual palette system for the thermal dashboard.
// Each Theme holds all colors, gradients, and pre-computed LUTs needed to
// render the UI. Built-in themes are registered in the package-level Registry.
package theme

import (
	"fmt"
	"image/color"

	colorful "github.com/lucasb-eyer/go-colorful"
)

// SparkThresholds defines the warn/crit boundaries for per-dot coloring.
// Moved here from widgets to avoid circular imports when widgets consume themes.
type SparkThresholds struct {
	Warn float64
	Crit float64
}

// Theme defines the complete visual palette for the thermal dashboard.
type Theme struct {
	Name string // "classic", "iron", "mono", "frost"

	// -- Severity gradient (sparklines) --
	GradientLow  colorful.Color // e.g. green (#22c55e)
	GradientMid  colorful.Color // e.g. yellow (#eab308)
	GradientHigh colorful.Color // e.g. red (#ef4444)

	// Pre-computed LUTs (generated by Init from the above anchors)
	lowMidLUT  [101]string // ANSI escapes: GradientLow -> GradientMid
	midHighLUT [101]string // ANSI escapes: GradientMid -> GradientHigh
	lowANSI    string      // cached: truecolorFg(GradientLow)
	highANSI   string      // cached: truecolorFg(GradientHigh)

	// -- Overall thermal gradient (headline bar) --
	OverallGradient [5]ThermalLevel

	// -- Category thermal gradient (category boxes) --
	CategoryGradient [5]ThermalLevel

	// -- Threat colors (alerts, status indicators) --
	ThreatColors [4]color.Color // indexed by ThreatLevel (Cool/Warm/Hot/Meltdown)

	// -- Session phase colors (session diamonds) --
	SessionPhase SessionPhaseColors

	// -- Gauge dot colors (sparkline row indicators) --
	GaugeDots [4]GaugeDotColor // CPU, MEM, COMP, GPU

	// -- Accent color (breathing agent icons) --
	AccentR, AccentG, AccentB float64 // base RGB for breathing modulation

	// -- Offline / special states --
	OfflineFg          color.Color      // quip text color when offline
	OfflineBg          color.Color      // background when offline
	OfflineSparkColors []colorful.Color // rainbow replacement for offline sparklines
	OfflineSparkANSI   []string         // pre-computed ANSI escapes (derived by Init)

	// -- Chrome (UI frame, help text, dim elements) --
	DimColor  color.Color // gray -- muted/inactive text
	HelpColor color.Color // help text descriptions
	IdleColor color.Color // idle state indicator and quip text

	// -- Rate display colors --
	SpawnColor color.Color // warm/spawn rate text
	DeathColor color.Color // cool/death rate text
	NetColor   color.Color // net rate text
}

// ThermalLevel pairs foreground and background for a heat level.
type ThermalLevel struct {
	Fg color.Color
	Bg color.Color
}

// SessionPhaseColors holds the 5 escalation states.
type SessionPhaseColors struct {
	Idle      color.Color // no activity
	Active    color.Color // shells below threshold
	Language  color.Color // runtime category detected
	Build     color.Color // build tools active
	Explosion color.Color // shell count above threshold
}

// GaugeDotColor defines a colored dot indicator for sparkline rows.
type GaugeDotColor struct {
	Char         string      // glyph (usually "●")
	Color        color.Color // lipgloss color for styled rendering
	ANSIOverride string      // explicit ANSI escape (e.g. "\033[37m" for 16-color); if set, Init skips truecolor derivation
	ANSI         string      // raw ANSI color escape (set by Init from ANSIOverride or truecolor derivation)
	Formatted    string      // pre-computed: ANSI + Char + reset + space (derived by Init)
}

// Init pre-computes LUTs and derived ANSI strings. Called once at theme load.
func (t *Theme) Init() {
	for i := 0; i <= 100; i++ {
		ratio := float64(i) / 100.0
		t.lowMidLUT[i] = truecolorFg(t.GradientLow.BlendHcl(t.GradientMid, ratio).Clamped())
		t.midHighLUT[i] = truecolorFg(t.GradientMid.BlendHcl(t.GradientHigh, ratio).Clamped())
	}
	t.lowANSI = truecolorFg(t.GradientLow)
	t.highANSI = truecolorFg(t.GradientHigh)

	for i := range t.GaugeDots {
		d := &t.GaugeDots[i]
		if d.ANSIOverride != "" {
			d.ANSI = d.ANSIOverride
		} else {
			d.ANSI = truecolorFgFromColor(d.Color)
		}
		d.Formatted = d.ANSI + d.Char + "\033[0m "
	}

	// Pre-compute offline rainbow ANSI escapes
	t.OfflineSparkANSI = make([]string, len(t.OfflineSparkColors))
	for i, c := range t.OfflineSparkColors {
		t.OfflineSparkANSI[i] = truecolorFg(c)
	}
}

// SeverityColor returns a truecolor ANSI escape for a value relative to
// thresholds. Interpolates low->mid below warn, mid->high between warn
// and crit, solid high above crit. Uses pre-computed LUTs.
func (t *Theme) SeverityColor(v float64, thresh *SparkThresholds) string {
	if thresh == nil {
		return t.lowANSI
	}
	switch {
	case v >= thresh.Crit:
		return t.highANSI
	case v >= thresh.Warn:
		ratio := (v - thresh.Warn) / (thresh.Crit - thresh.Warn)
		return t.midHighLUT[blendIndex(ratio)]
	default:
		if thresh.Warn <= 0 {
			return t.lowANSI
		}
		ratio := v / thresh.Warn
		return t.lowMidLUT[blendIndex(ratio)]
	}
}

// blendIndex clamps a ratio to [0,1] and converts to a LUT index 0-100.
func blendIndex(ratio float64) int {
	if ratio <= 0 {
		return 0
	}
	if ratio >= 1 {
		return 100
	}
	return int(ratio * 100)
}

// truecolorFg emits \033[38;2;R;G;Bm for 24-bit foreground color.
func truecolorFg(c colorful.Color) string {
	r, g, b := c.RGB255()
	return fmt.Sprintf("\033[38;2;%d;%d;%dm", r, g, b)
}

// truecolorFgFromColor converts a color.Color to a truecolor ANSI escape.
func truecolorFgFromColor(c color.Color) string {
	r, g, b, _ := c.RGBA()
	return fmt.Sprintf("\033[38;2;%d;%d;%dm", r>>8, g>>8, b>>8)
}

// mustHex parses a hex color string or panics. Used by palette constructors.
func mustHex(hex string) colorful.Color {
	c, err := colorful.Hex(hex)
	if err != nil {
		panic(fmt.Sprintf("theme: invalid hex color %q: %v", hex, err))
	}
	return c
}
