// Package theme defines the visual palette system for the thermal dashboard.
// Each Theme holds all colors, gradients, and pre-computed LUTs needed to
// render the UI. Built-in themes are registered in the package-level Registry.
package theme

import (
	"fmt"
	"image/color"

	"charm.land/bubbles/v2/help"
	colorful "github.com/lucasb-eyer/go-colorful"
)

// SparkThresholds defines the warn/crit boundaries for per-dot coloring.
// Moved here from widgets to avoid circular imports when widgets consume themes.
type SparkThresholds struct {
	Warn float64
	Crit float64
}

// Theme defines the complete visual palette for the thermal dashboard.
type Theme struct {
	Name string // registered theme name — see Registry in registry.go

	// -- Severity gradient (sparklines) --
	GradientLow  colorful.Color // e.g. green (#22c55e)
	GradientMid  colorful.Color // e.g. yellow (#eab308)
	GradientHigh colorful.Color // e.g. red (#ef4444)

	// Pre-computed LUTs (generated by Init from the above anchors)
	lowMidLUT  [101]string // ANSI escapes: GradientLow -> GradientMid
	midHighLUT [101]string // ANSI escapes: GradientMid -> GradientHigh
	lowANSI    string      // cached: truecolorFg(GradientLow)
	highANSI   string      // cached: truecolorFg(GradientHigh)

	// Dimmed variants — HCL-dimmed copies for rendering behind overlays.
	dimLowMidLUT  [101]string
	dimMidHighLUT [101]string
	dimLowANSI    string
	dimHighANSI   string

	// -- Overall thermal gradient (headline bar) --
	OverallGradient [5]ThermalLevel

	// Continuous-gradient LUT for the segment-LCD temperature readout.
	// Maps temperature value 0..99 to a truecolor fg ANSI escape produced
	// by BlendHcl between adjacent OverallGradient[i].Fg anchors.
	overallTempLUT  [100]string
	overallLevelLUT [5]string // band-anchor fg ANSI; stable within a threat level

	// batteryGrainLUT maps battery grain count (0=empty, 22=full) to an HCL
	// blend across the ok→warn→crit anchors (gradient[1..3]). Lets the
	// battery widget tick one hue step per grain without recomputing the
	// blend on every render.
	batteryGrainLUT [23]color.Color

	// -- Category thermal gradient (category boxes) --
	CategoryGradient [5]ThermalLevel

	// RailCriticalOverride, when non-nil, replaces CategoryGradient[4].Fg
	// as the peak color for the headline's build/shell heat-rail
	// underlines. CategoryGradient Fgs were designed as half of an Fg+Bg
	// pair; stripped of their paired Bg, a few themes' critical Fgs
	// (Iron's 229 cream-white, Mono's 230 near-white) read as flashbulb
	// harsh when used as a solo accent on the pinned iconBg. Themes
	// that prefer an ember tone in the same hue family set this field;
	// themes that leave it nil retain legacy CategoryGradient behavior.
	RailCriticalOverride color.Color

	// -- Heat bloom --
	// BloomRamp defines four heat stops (COOL/WARM/HOT/MELTDOWN). Each stop
	// holds a Core→Edge gradient. Init pre-computes a (heat × radial) LUT
	// for O(1) lookup at render time.
	BloomRamp    [4]BloomRampStop
	bloomCoreLUT [100][100]colorful.Color

	// -- Threat colors (alerts, status indicators) --
	ThreatColors [4]color.Color // indexed by ThreatLevel (Cool/Warm/Hot/Meltdown)

	// -- Session phase colors (session diamonds) --
	SessionPhase SessionPhaseColors

	// -- Gauge dot colors (sparkline row indicators) --
	GaugeDots [4]GaugeDotColor // CPU, MEM, COMP, GPU

	// -- Accent color (breathing agent icons) --
	AccentR, AccentG, AccentB float64 // base RGB for breathing modulation

	// -- Offline / special states --
	OfflineFg          color.Color      // quip text color when offline
	OfflineBg          color.Color      // background when offline
	OfflineSparkColors []colorful.Color // rainbow replacement for offline sparklines
	OfflineSparkANSI   []string         // pre-computed ANSI escapes (derived by Init)

	// -- Chrome (UI frame, help text, dim elements) --
	DimColor  color.Color // gray -- muted/inactive text
	HelpColor color.Color // help text descriptions
	IdleColor color.Color // idle state indicator and quip text

	// -- Rate display colors --
	SpawnColor color.Color // warm/spawn rate text
	DeathColor color.Color // cool/death rate text
	NetColor   color.Color // net rate text

	helpStyles help.Styles
}

// ThermalLevel pairs foreground and background for a heat level.
type ThermalLevel struct {
	Fg color.Color
	Bg color.Color
}

// BloomRampStop defines one heat-level stop in the HeatBloom color gradient.
// Core is the ellipse-center color (peak alpha); Edge is the outer falloff
// color (alpha approaches 0). Both participate in HCL-blended interpolation.
type BloomRampStop struct {
	Core colorful.Color
	Edge colorful.Color
}

// SessionPhaseColors holds the 5 escalation states.
type SessionPhaseColors struct {
	Idle      color.Color // no activity
	Active    color.Color // shells below threshold
	Language  color.Color // runtime category detected
	Build     color.Color // build tools active
	Explosion color.Color // shell count above threshold
}

// GaugeDotColor defines a colored dot indicator for sparkline rows.
type GaugeDotColor struct {
	Char         string      // glyph (usually "●")
	Color        color.Color // lipgloss color for styled rendering
	ANSIOverride string      // explicit ANSI escape (e.g. "\033[37m" for 16-color); if set, Init skips truecolor derivation
	ANSI         string      // raw ANSI color escape (set by Init from ANSIOverride or truecolor derivation)
	DimmedANSI   string      // HCL-dimmed variant used behind overlays (set by Init)
	Formatted    string      // pre-computed: ANSI + Char + reset + space (derived by Init)
}

// DimOverlayRatio scales lightness and chroma of theme colors when they
// render behind an overlay. 1.0 = full color, 0 = black. Tuned to leave
// sparklines readable as live motion but visually recede behind help text.
const DimOverlayRatio = 0.5

// Init pre-computes LUTs and derived ANSI strings. Called once at theme load.
func (t *Theme) Init() {
	dimLow := dimColorful(t.GradientLow, DimOverlayRatio)
	dimMid := dimColorful(t.GradientMid, DimOverlayRatio)
	dimHigh := dimColorful(t.GradientHigh, DimOverlayRatio)
	for i := 0; i <= 100; i++ {
		ratio := float64(i) / 100.0
		t.lowMidLUT[i] = truecolorFg(t.GradientLow.BlendHcl(t.GradientMid, ratio).Clamped())
		t.midHighLUT[i] = truecolorFg(t.GradientMid.BlendHcl(t.GradientHigh, ratio).Clamped())
		t.dimLowMidLUT[i] = truecolorFg(dimLow.BlendHcl(dimMid, ratio).Clamped())
		t.dimMidHighLUT[i] = truecolorFg(dimMid.BlendHcl(dimHigh, ratio).Clamped())
	}
	t.lowANSI = truecolorFg(t.GradientLow)
	t.highANSI = truecolorFg(t.GradientHigh)
	t.dimLowANSI = truecolorFg(dimLow)
	t.dimHighANSI = truecolorFg(dimHigh)

	for i := range t.GaugeDots {
		d := &t.GaugeDots[i]
		if d.ANSIOverride != "" {
			d.ANSI = d.ANSIOverride
			d.DimmedANSI = d.ANSIOverride // 16-color palettes have no truecolor dim variant; reuse.
		} else {
			d.ANSI = truecolorFgFromColor(d.Color)
			d.DimmedANSI = truecolorDimmedFgFromColor(d.Color, DimOverlayRatio)
		}
		d.Formatted = d.ANSI + d.Char + "\033[0m "
	}

	// Pre-compute offline rainbow ANSI escapes
	t.OfflineSparkANSI = make([]string, len(t.OfflineSparkColors))
	for i, c := range t.OfflineSparkColors {
		t.OfflineSparkANSI[i] = truecolorFg(c)
	}

	t.helpStyles = buildHelpStyles(t)

	// Continuous OverallGradient LUT: blend across the 5 Fg anchors so the
	// LCD readout hue drifts smoothly across 0..99 instead of snapping to
	// the four threat bands.
	var anchors [5]colorful.Color
	for i := range t.OverallGradient {
		anchors[i] = colorfulFromColor(t.OverallGradient[i].Fg)
	}
	for v := 0; v < 100; v++ {
		pos := float64(v) / 99.0 * 4.0 // 0..4 across the five anchors
		seg := int(pos)
		if seg >= 4 {
			seg = 3
		}
		ratio := pos - float64(seg)
		blended := anchors[seg].BlendHcl(anchors[seg+1], ratio).Clamped()
		t.overallTempLUT[v] = truecolorFg(blended)
	}

	// Per-level fg LUT: the LCD's degree glyph reads from this so its color
	// only changes on band transitions, not on every value step.
	for i := range t.OverallGradient {
		t.overallLevelLUT[i] = truecolorFg(colorfulFromColor(t.OverallGradient[i].Fg))
	}

	// Battery grain LUT: 23 entries, one per grain count in [0,22]. Spans
	// gradient[1]→[2]→[3] with gradient[2] at the midpoint so the battery
	// reads cool at full, warn at half, hot at empty.
	for n := 0; n <= 22; n++ {
		tt := 1.0 - float64(n)/22.0
		var blended colorful.Color
		if tt <= 0.5 {
			blended = anchors[1].BlendHcl(anchors[2], tt*2).Clamped()
		} else {
			blended = anchors[2].BlendHcl(anchors[3], (tt-0.5)*2).Clamped()
		}
		r, g, b := blended.RGB255()
		t.batteryGrainLUT[n] = color.NRGBA{R: r, G: g, B: b, A: 255}
	}

	// Heat-bloom LUT: 100 heat rows × 100 radial columns. Between the four
	// BloomRamp stops we have 3 segments; within each segment, HCL-blend
	// both Core and Edge anchors, then HCL-blend Core→Edge across radial.
	for hi := 0; hi < 100; hi++ {
		heat := float64(hi) / 99.0
		pos := heat * 3.0
		seg := int(pos)
		if seg >= 3 {
			seg = 2
		}
		segRatio := pos - float64(seg)
		core := t.BloomRamp[seg].Core.BlendHcl(t.BloomRamp[seg+1].Core, segRatio).Clamped()
		edge := t.BloomRamp[seg].Edge.BlendHcl(t.BloomRamp[seg+1].Edge, segRatio).Clamped()
		for ri := 0; ri < 100; ri++ {
			radial := float64(ri) / 99.0
			t.bloomCoreLUT[hi][ri] = core.BlendHcl(edge, radial).Clamped()
		}
	}
}

// BloomColor returns the bloom's pre-blended color for a given heat scalar
// in [0,1] and radial distance in [0,1] (0=core, 1=edge). The returned
// colorful.Color is ready for alpha-blend compositing against a fallback.
func (t *Theme) BloomColor(heat, radial float64) colorful.Color {
	hi := bloomLUTIndex(heat)
	ri := bloomLUTIndex(radial)
	return t.bloomCoreLUT[hi][ri]
}

// bloomLUTIndex clamps a [0,1] ratio to a 0..99 LUT index.
func bloomLUTIndex(r float64) int {
	if r <= 0 {
		return 0
	}
	if r >= 1 {
		return 99
	}
	return int(r * 99)
}

// OverallTemperatureFg returns the precomputed truecolor fg ANSI escape for
// a temperature value 0..99. Out-of-range values clamp.
func (t *Theme) OverallTemperatureFg(value int) string {
	return t.overallTempLUT[clampTemp(value)]
}

// OverallLevelFg returns the truecolor fg ANSI escape for a threat level
// (0..4). The LCD degree glyph uses this so it only repaints when the
// level transitions — not on every value step.
func (t *Theme) OverallLevelFg(level int) string {
	if level < 0 {
		level = 0
	}
	if level > 4 {
		level = 4
	}
	return t.overallLevelLUT[level]
}

// BatteryGrainColor returns the pre-blended HCL color for a battery grain
// count in [0,22]. Out-of-range values clamp.
func (t *Theme) BatteryGrainColor(n int) color.Color {
	if n < 0 {
		n = 0
	}
	if n > 22 {
		n = 22
	}
	return t.batteryGrainLUT[n]
}

func clampTemp(v int) int {
	if v < 0 {
		return 0
	}
	if v > 99 {
		return 99
	}
	return v
}

// colorfulFromColor converts an image/color.Color (lipgloss palette index or
// truecolor) to colorful.Color in [0,1] component space.
func colorfulFromColor(c color.Color) colorful.Color {
	r, g, b, _ := c.RGBA()
	return colorful.Color{
		R: float64(r) / 65535.0,
		G: float64(g) / 65535.0,
		B: float64(b) / 65535.0,
	}
}

// SeverityColor returns a truecolor ANSI escape for a value relative to
// thresholds. Interpolates low->mid below warn, mid->high between warn
// and crit, solid high above crit. Uses pre-computed LUTs.
func (t *Theme) SeverityColor(v float64, thresh *SparkThresholds) string {
	if thresh == nil {
		return t.lowANSI
	}
	switch {
	case v >= thresh.Crit:
		return t.highANSI
	case v >= thresh.Warn:
		ratio := (v - thresh.Warn) / (thresh.Crit - thresh.Warn)
		return t.midHighLUT[blendIndex(ratio)]
	default:
		if thresh.Warn <= 0 {
			return t.lowANSI
		}
		ratio := v / thresh.Warn
		return t.lowMidLUT[blendIndex(ratio)]
	}
}

// SeverityColorDimmed mirrors SeverityColor but reads the HCL-dimmed LUTs,
// producing theme-faithful muted colors for rendering behind overlays.
func (t *Theme) SeverityColorDimmed(v float64, thresh *SparkThresholds) string {
	if thresh == nil {
		return t.dimLowANSI
	}
	switch {
	case v >= thresh.Crit:
		return t.dimHighANSI
	case v >= thresh.Warn:
		ratio := (v - thresh.Warn) / (thresh.Crit - thresh.Warn)
		return t.dimMidHighLUT[blendIndex(ratio)]
	default:
		if thresh.Warn <= 0 {
			return t.dimLowANSI
		}
		ratio := v / thresh.Warn
		return t.dimLowMidLUT[blendIndex(ratio)]
	}
}

// blendIndex clamps a ratio to [0,1] and converts to a LUT index 0-100.
func blendIndex(ratio float64) int {
	if ratio <= 0 {
		return 0
	}
	if ratio >= 1 {
		return 100
	}
	return int(ratio * 100)
}

// truecolorFg emits \033[38;2;R;G;Bm for 24-bit foreground color.
func truecolorFg(c colorful.Color) string {
	r, g, b := c.RGB255()
	return fmt.Sprintf("\033[38;2;%d;%d;%dm", r, g, b)
}

// truecolorFgFromColor converts a color.Color to a truecolor ANSI escape.
func truecolorFgFromColor(c color.Color) string {
	r, g, b, _ := c.RGBA()
	return fmt.Sprintf("\033[38;2;%d;%d;%dm", r>>8, g>>8, b>>8)
}

// truecolorDimmedFgFromColor returns a dimmed truecolor ANSI escape by
// scaling the color's HCL chroma and lightness by ratio.
func truecolorDimmedFgFromColor(c color.Color, ratio float64) string {
	r, g, b, _ := c.RGBA()
	cf := colorful.Color{R: float64(r>>8) / 255.0, G: float64(g>>8) / 255.0, B: float64(b>>8) / 255.0}
	return truecolorFg(dimColorful(cf, ratio))
}

// dimColorful scales HCL chroma and lightness by ratio. Preserves hue so
// dimmed colors still read as theme-faithful muted variants.
func dimColorful(c colorful.Color, ratio float64) colorful.Color {
	h, ch, l := c.Hcl()
	return colorful.Hcl(h, ch*ratio, l*ratio).Clamped()
}

// mustHex parses a hex color string or panics. Used by palette constructors.
func mustHex(hex string) colorful.Color {
	c, err := colorful.Hex(hex)
	if err != nil {
		panic(fmt.Sprintf("theme: invalid hex color %q: %v", hex, err))
	}
	return c
}
